### ISSUE TITLE
Support UNB Type hashes

### ISSUE THREAD

**Issue by splitbrain** [migratetoflarum/old-passwords#4]
Hi, I'm in the process of migrating a Forum from [Unclassified Newsboard](http://newsboard.unclassified.de/) to Flarum. They rolled their own MD5 based hashing and it would be awesome if your extension could support it.

I implemented their hashing method for DokuWiki here:
https://github.com/splitbrain/dokuwiki/blob/fe5b5b2a3afab46acfb4124abcb9cc73412ee07a/inc/PassHash.php#L348-L367

**Comment by clarkwinkelmann** [comment]
Hi! Thanks for the report.

Would you be interested in submitting a PR yourself ?

Otherwise I'll happily add the support when I find some time, hopefully next week. Could you provide me with some example data for tests ? Is the salt stored in a separate column, or it it always part of the hashed value ? Could you provide me with an example for the password `correcthorsebatterystaple` and a given salt like `12345678` ?

**Comment by clarkwinkelmann** [comment]
I have implemented the hasher and tagged version 0.5.0.

Let me know how it works! Thanks for the help with the example code and test!

**Comment by splitbrain** [comment]
Thanks for merging. Any chance you could update the version for composer?

**Comment by clarkwinkelmann** [comment]
It's tagged as version 0.5.0. You should be able to install it with `composer require migratetoflarum/old-passwords`.

Let me know if that's not working.

**Comment by splitbrain** [comment]
worked. Thanks a lot!
